apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-cash-daemon.fullname" . }}
  labels:
    {{- include "bitcoin-cash-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: p2p
      port: {{ include "bitcoin-cash-daemon.p2p" . }}
      targetPort: p2p
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{.Values.service.port.p2p}}
      {{ end }}
    - name: rpc
      port: {{ include "bitcoin-cash-daemon.rpc" . }}
      targetPort: rpc
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{.Values.service.port.rpc}}
      {{ end }}
  selector:
    {{- include "bitcoin-cash-daemon.selectorLabels" . | nindent 4 }}
