apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # hcloud
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/type: lb11
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.validator }}
    - port: {{ .Values.service.port.sentinel.api }}
      targetPort: sentinel-api
      protocol: TCP
      name: sentinel-api
    {{- end }}
    {{- if .Values.api }}
    - port: {{ .Values.service.port.api }}
      targetPort: api
      protocol: TCP
      name: api
    {{- end }}
    {{- if .Values.rpc.enabled }}
    - port: {{ include "gateway.rpc" . }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- end }}
    - port: {{ include "gateway.p2p" . }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
