global:
  net: mainnet
  gateway:
    enabled: true
    name: gateway
  images:
    alpine:
      tag: latest
      hash: 4edbd2beb5f78b1014028f4fbb99f3237d9561100b6881aabbf5acce2c4f9454
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

gateway:
  fullnameOverride: gateway

thornode:
  fullnameOverride: thornode

bifrost:
  fullnameOverride: bifrost

midgard:
  enabled: false
  fullnameOverride: midgard

binance-daemon:
  fullnameOverride: binance-daemon

bitcoin-daemon:
  fullnameOverride: bitcoin-daemon

litecoin-daemon:
  fullnameOverride: litecoin-daemon

bitcoin-cash-daemon:
  fullnameOverride: bitcoin-cash-daemon

ethereum-daemon:
  fullnameOverride: ethereum-daemon

dogecoin-daemon:
  fullnameOverride: dogecoin-daemon

gaia-daemon:
  fullnameOverride: gaia-daemon
  enabled: false

avalanche-daemon:
  fullnameOverride: avalanche-daemon
